### PR TITLE
Fix colors.

### PR DESCRIPTION
**Pull request by perpetualCreations**
Remove duplicate entries #928374 in `gruvbox.txt`, added missing colors listed on [morhetz/gruvbox](https://github.com/morhetz/gruvbox).
As a sanity check, I wrote a quick script to check for any duplicates I may have missed.

```python
with open("gruvbox.txt") as color_handle:
    data = color_handle.read().split("\n")
    for color in data:
        if data.count(color) > 1:
            raise Exception("Duplicate color", color)
```

I'm not sure if there's a technical reason why these colors were left out, best guess is that they resulted in manufactured images not matching common foreground/background colors, in which case, I'll revise this PR, however it fixed light colors being rendered as yellow, and grays turning out aqua and purple.

Thanks for making this project.

### CODE REVIEW

**Comment by paulopacitti** [comment]
Hey @perpetualCreations , thanks for submitting a pull request 🚀  I'll be testing your PR local in my machine soon and getting back to you ☎️

**Comment by paulopacitti** [comment]
I did some tests with my favorite image, I'm not sure if I liked the result:
- Original:
will-fuller-40930-unsplash
- Current `gruvbox-factory`:
gruvbox_will-fuller-40930-unsplash_1
- Your proposal:
gruvbox_will-fuller-40930-unsplash_2

I think I've decided to omit the light colors to prevent a lot of "white" colors. What you guys think (`gruvbox-factory` lovers)? ✨

**Comment by samyakbardiya** [comment]
looks GREAT 👍🏻

**Comment by paulopacitti** [comment]
I think I'll maintain both versions, being your new version accessible with a flag 😉

**Comment by paulopacitti** [comment]
I'll merge like this and then add both versions later

**Pull request merged**
